/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as OtaBusterRouteImport } from './routes/ota-buster'
import { Route as OtaBusterIndexRouteImport } from './routes/ota-buster.index'
import { Route as OtaBusterPerformanceRouteImport } from './routes/ota-buster.performance'
import { Route as OtaBusterSegmentsRouteImport } from './routes/ota-buster.segments'
import { Route as OtaBusterSettingsRouteImport } from './routes/ota-buster.settings'
import { Route as OtaBusterStageStageIdRouteImport } from './routes/ota-buster.stage.$stageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaBusterRoute = OtaBusterRouteImport.update({
  id: '/ota-buster',
  path: '/ota-buster',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaBusterIndexRoute = OtaBusterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OtaBusterRoute,
} as any)
const OtaBusterPerformanceRoute = OtaBusterPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => OtaBusterRoute,
} as any)
const OtaBusterSegmentsRoute = OtaBusterSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => OtaBusterRoute,
} as any)
const OtaBusterSettingsRoute = OtaBusterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OtaBusterRoute,
} as any)
const OtaBusterStageStageIdRoute = OtaBusterStageStageIdRouteImport.update({
  id: '/stage/$stageId',
  path: '/stage/$stageId',
  getParentRoute: () => OtaBusterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/ota-buster': typeof OtaBusterRouteWithChildren
  '/ota-buster/performance': typeof OtaBusterPerformanceRoute
  '/ota-buster/segments': typeof OtaBusterSegmentsRoute
  '/ota-buster/settings': typeof OtaBusterSettingsRoute
  '/ota-buster/': typeof OtaBusterIndexRoute
  '/ota-buster/stage/$stageId': typeof OtaBusterStageStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/ota-buster/performance': typeof OtaBusterPerformanceRoute
  '/ota-buster/segments': typeof OtaBusterSegmentsRoute
  '/ota-buster/settings': typeof OtaBusterSettingsRoute
  '/ota-buster': typeof OtaBusterIndexRoute
  '/ota-buster/stage/$stageId': typeof OtaBusterStageStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/ota-buster': typeof OtaBusterRouteWithChildren
  '/ota-buster/performance': typeof OtaBusterPerformanceRoute
  '/ota-buster/segments': typeof OtaBusterSegmentsRoute
  '/ota-buster/settings': typeof OtaBusterSettingsRoute
  '/ota-buster/': typeof OtaBusterIndexRoute
  '/ota-buster/stage/$stageId': typeof OtaBusterStageStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-templates'
    | '/ota-buster'
    | '/ota-buster/performance'
    | '/ota-buster/segments'
    | '/ota-buster/settings'
    | '/ota-buster/'
    | '/ota-buster/stage/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-templates'
    | '/ota-buster/performance'
    | '/ota-buster/segments'
    | '/ota-buster/settings'
    | '/ota-buster'
    | '/ota-buster/stage/$stageId'
  id:
    | '__root__'
    | '/'
    | '/email-templates'
    | '/ota-buster'
    | '/ota-buster/performance'
    | '/ota-buster/segments'
    | '/ota-buster/settings'
    | '/ota-buster/'
    | '/ota-buster/stage/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  OtaBusterRoute: typeof OtaBusterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota-buster': {
      id: '/ota-buster'
      path: '/ota-buster'
      fullPath: '/ota-buster'
      preLoaderRoute: typeof OtaBusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota-buster/': {
      id: '/ota-buster/'
      path: '/'
      fullPath: '/ota-buster/'
      preLoaderRoute: typeof OtaBusterIndexRouteImport
      parentRoute: typeof OtaBusterRoute
    }
    '/ota-buster/performance': {
      id: '/ota-buster/performance'
      path: '/performance'
      fullPath: '/ota-buster/performance'
      preLoaderRoute: typeof OtaBusterPerformanceRouteImport
      parentRoute: typeof OtaBusterRoute
    }
    '/ota-buster/segments': {
      id: '/ota-buster/segments'
      path: '/segments'
      fullPath: '/ota-buster/segments'
      preLoaderRoute: typeof OtaBusterSegmentsRouteImport
      parentRoute: typeof OtaBusterRoute
    }
    '/ota-buster/settings': {
      id: '/ota-buster/settings'
      path: '/settings'
      fullPath: '/ota-buster/settings'
      preLoaderRoute: typeof OtaBusterSettingsRouteImport
      parentRoute: typeof OtaBusterRoute
    }
    '/ota-buster/stage/$stageId': {
      id: '/ota-buster/stage/$stageId'
      path: '/stage/$stageId'
      fullPath: '/ota-buster/stage/$stageId'
      preLoaderRoute: typeof OtaBusterStageStageIdRouteImport
      parentRoute: typeof OtaBusterRoute
    }
  }
}

interface OtaBusterRouteChildren {
  OtaBusterPerformanceRoute: typeof OtaBusterPerformanceRoute
  OtaBusterSegmentsRoute: typeof OtaBusterSegmentsRoute
  OtaBusterSettingsRoute: typeof OtaBusterSettingsRoute
  OtaBusterIndexRoute: typeof OtaBusterIndexRoute
  OtaBusterStageStageIdRoute: typeof OtaBusterStageStageIdRoute
}

const OtaBusterRouteChildren: OtaBusterRouteChildren = {
  OtaBusterPerformanceRoute: OtaBusterPerformanceRoute,
  OtaBusterSegmentsRoute: OtaBusterSegmentsRoute,
  OtaBusterSettingsRoute: OtaBusterSettingsRoute,
  OtaBusterIndexRoute: OtaBusterIndexRoute,
  OtaBusterStageStageIdRoute: OtaBusterStageStageIdRoute,
}

const OtaBusterRouteWithChildren = OtaBusterRoute._addFileChildren(
  OtaBusterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailTemplatesRoute: EmailTemplatesRoute,
  OtaBusterRoute: OtaBusterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
